"""empty message

Revision ID: 04f9257472bf
Revises: 
Create Date: 2025-03-25 11:22:56.521272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f9257472bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('git_hub_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('git_hub_event', schema=None) as batch_op:
        batch_op.drop_column('event_type')

    # ### end Alembic commands ###
