"""empty message

Revision ID: 14dd2c545e86
Revises: 635d9d955ba2
Create Date: 2025-04-03 08:46:23.195926

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "14dd2c545e86"
down_revision = "635d9d955ba2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("SECRET_GITHUB_username", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("SECRET_GITHUB_username")

    # ### end Alembic commands ###
