"""empty message

Revision ID: 293e81ee87e6
Revises: 95959d6853ee
Create Date: 2025-04-23 17:49:51.382490

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "293e81ee87e6"
down_revision = "95959d6853ee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "SECRET_GITHUB_TOKEN",
                sa.String(length=255),
                nullable=False,
                server_default="default_token",
            )
        )
        # Check if the column exists before attempting to drop it
        conn = op.get_bind()
        inspector = sa.inspect(conn)
        columns = [col["name"] for col in inspector.get_columns("user")]
        if "SECRET_GITHUB_token" in columns:
            batch_op.drop_column("SECRET_GITHUB_token")
        batch_op.drop_column("linkedin_access_token")
        batch_op.drop_column("linkedin_user_urn")

    # Move the `ALTER COLUMN` operation outside the `batch_alter_table` context
    op.alter_column("user", "SECRET_GITHUB_TOKEN", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "linkedin_user_urn", sa.VARCHAR(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "linkedin_access_token",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            )
        )
        # Check if the column exists before altering it
        conn = op.get_bind()
        inspector = sa.inspect(conn)
        columns = [col["name"] for col in inspector.get_columns("user")]
        if "SECRET_GITHUB_token" in columns:
            batch_op.add_column(
                sa.Column(
                    "SECRET_GITHUB_token",
                    sa.String(),
                    nullable=False,
                    server_default="default_token",
                )
            )
            op.alter_column("user", "SECRET_GITHUB_token", server_default=None)
        batch_op.drop_column("SECRET_GITHUB_TOKEN")

    # ### end Alembic commands ###
