"""empty message

Revision ID: 293e81ee87e6
Revises: 95959d6853ee
Create Date: 2025-04-23 17:49:51.382490

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "293e81ee87e6"
down_revision = "95959d6853ee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "SECRET_GITHUB_TOKEN",
                sa.String(length=255),
                nullable=False,
                server_default="default_token",
            )
        )
        batch_op.drop_column("github_token")
        batch_op.drop_column("linkedin_access_token")
        batch_op.drop_column("linkedin_user_urn")

    # Move the `ALTER COLUMN` operation outside the `batch_alter_table` context
    op.alter_column("user", "SECRET_GITHUB_TOKEN", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "linkedin_user_urn", sa.VARCHAR(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "linkedin_access_token",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("github_token", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.drop_column("SECRET_GITHUB_TOKEN")

    # ### end Alembic commands ###
