"""empty message

Revision ID: 62718f87c92d
Revises: e3d6a50bbed3
Create Date: 2025-04-15 19:03:24.395843

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "62718f87c92d"
down_revision = "e3d6a50bbed3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("email", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("avatar_url", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "extra_metadata", postgresql.JSON(astext_type=sa.Text()), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("extra_metadata")
        batch_op.drop_column("avatar_url")
        batch_op.drop_column("email")
        batch_op.drop_column("name")

    # ### end Alembic commands ###
