"""empty message

Revision ID: 69c1775f500f
Revises: 293e81ee87e6
Create Date: 2025-04-23 20:03:00.683126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c1775f500f'
down_revision = '293e81ee87e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SECRET_GITHUB_id', sa.String(length=255), nullable=False, server_default='default_id'))
        # Remove the default value after the column is added
        op.alter_column('user', 'SECRET_GITHUB_id', server_default=None)
        batch_op.add_column(sa.Column('SECRET_GITHUB_username', sa.String(), nullable=True))
        batch_op.drop_constraint('user_github_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['SECRET_GITHUB_id'])
        batch_op.drop_column('github_id')
        batch_op.drop_column('github_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_username', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('github_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_github_id_key', ['github_id'])
        batch_op.drop_column('SECRET_GITHUB_username')
        batch_op.drop_column('SECRET_GITHUB_id')

    # ### end Alembic commands ###
