"""empty message

Revision ID: 95959d6853ee
Revises: 62718f87c92d
Create Date: 2025-04-16 02:03:18.334714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95959d6853ee'
down_revision = '62718f87c92d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_access_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('linkedin_user_urn', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('linkedin_user_urn')
        batch_op.drop_column('linkedin_access_token')

    # ### end Alembic commands ###
