"""Initial migration

Revision ID: 975261853af3
Revises: 
Create Date: 2025-03-19 13:28:34.931452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '975261853af3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.String(), nullable=False),
    sa.Column('linkedin_id', sa.String(), nullable=True),
    sa.Column('github_token', sa.String(), nullable=False),
    sa.Column('linkedin_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('linkedin_id')
    )
    op.drop_table('test_table')
    op.drop_table('client')
    with op.batch_alter_table('git_hub_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('repo_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('commit_url', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.alter_column('commit_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('url')
        batch_op.drop_column('author')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('repo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('git_hub_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repo', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('commit_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('commit_url')
        batch_op.drop_column('repo_name')
        batch_op.drop_column('user_id')

    op.create_table('client',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('database_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='client_pkey'),
    sa.UniqueConstraint('database_url', name='client_database_url_key'),
    sa.UniqueConstraint('name', name='client_name_key')
    )
    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_table_pkey')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
