"""Initial

Revision ID: 98d3c31728c0
Revises: 
Create Date: 2025-03-25 16:54:45.405430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d3c31728c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.String(), nullable=False),
    sa.Column('linkedin_id', sa.String(), nullable=True),
    sa.Column('github_token', sa.String(), nullable=False),
    sa.Column('linkedin_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('linkedin_id')
    )
    op.create_table('git_hub_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=False),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('commit_url', sa.String(length=512), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('linkedin_post_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('git_hub_event')
    op.drop_table('user')
    # ### end Alembic commands ###
