"""empty message

Revision ID: e3d6a50bbed3
Revises: 14dd2c545e86
Create Date: 2025-04-09 10:48:17.279520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d6a50bbed3'
down_revision = '14dd2c545e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('git_hub_event', schema=None) as batch_op:
        batch_op.alter_column('commit_message',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('git_hub_event', schema=None) as batch_op:
        batch_op.alter_column('commit_message',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
