name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Secrets
        run: |
          echo "LINKEDIN_ACCESS_TOKEN is set to: ${LINKEDIN_ACCESS_TOKEN:+[REDACTED]}"
          echo "LINKEDIN_USER_ID is set to: ${LINKEDIN_USER_ID:+[REDACTED]}"
        env:
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          LINKEDIN_USER_ID: ${{ secrets.LINKEDIN_USER_ID }}