name: CI Tests

on:
  push:
    branches:
      - feature/github-actions-ci-integration
  pull_request:
    branches:
      - feature/github-actions-ci-integration

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Node.js dependencies
        run: |
          cd frontend
          npm install

      - name: Run backend tests
        env:
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          LINKEDIN_USER_ID: ${{ secrets.LINKEDIN_USER_ID }}
        run: |
          pytest --maxfail=1 --disable-warnings

      - name: Run frontend tests
        run: |
          cd frontend
          npm test -- --watchAll=false

      - name: Check for lint errors
        run: |
          cd frontend
          npm run lint

      - name: Verify environment variables
        run: |
          python -c "import os; assert os.getenv('LINKEDIN_ACCESS_TOKEN'), 'Missing LINKEDIN_ACCESS_TOKEN'; assert os.getenv('LINKEDIN_USER_ID'), 'Missing LINKEDIN_USER_ID'"