name: CI Tests

on:
  push:
    branches:
      - feature/github-actions-ci-integration
  pull_request:
    branches:
      - feature/github-actions-ci-integration

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Node.js dependencies
        run: |
          cd frontend
          npm install

      - name: Debug env vars
        run: |
          echo "LINKEDIN_CLIENT_ID=$LINKEDIN_CLIENT_ID"
          echo "LINKEDIN_CLIENT_SECRET=$LINKEDIN_CLIENT_SECRET"
        env:
          LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
          LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}


      - name: Run backend tests
        env:
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          LINKEDIN_USER_ID: ${{ secrets.LINKEDIN_USER_ID }}
          SQLALCHEMY_DATABASE_URI: ${{ secrets.SQLALCHEMY_DATABASE_URI }}
          LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
          LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}
          SEED_GITHUB_ID: ${{ secrets.SEED_GITHUB_ID }}
          SEED_GITHUB_USERNAME: ${{ secrets.SEED_GITHUB_USERNAME }}
          SEED_GITHUB_TOKEN: ${{ secrets.SEED_GITHUB_TOKEN }}
          SEED_LINKEDIN_ID: ${{ secrets.SEED_LINKEDIN_ID }}
          SEED_LINKEDIN_TOKEN: ${{ secrets.SEED_LINKEDIN_TOKEN }}
        run: |
          pytest --maxfail=1 --disable-warnings
          # TODO: Add frontend tests when working on the frontend
      # - name: Run frontend tests
      #   run: |
      #     cd frontend
      #     npm test -- --watchAll=false

      - name: Check for lint errors
        run: |
          cd frontend
          npm run lint

      - name: Verify environment variables
        run: |
          python -c "import os; assert os.getenv('LINKEDIN_ACCESS_TOKEN'), 'Missing LINKEDIN_ACCESS_TOKEN'; assert os.getenv('LINKEDIN_USER_ID'), 'Missing LINKEDIN_USER_ID'"